<?php
/**
 * ProviderApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Delta/Voip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Brand REST API
 *
 * OpenAPI spec version: 2.17.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Delta/Voip;

use \Delta/Voip\Configuration;
use \Delta/Voip\ApiException;
use \Delta/Voip\ObjectSerializer;

/**
 * ProviderApiTest Class Doc Comment
 *
 * @category Class
 * @package  Delta/Voip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProviderApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for brandLogoBrandItem
     *
     * Retrieves a Brand resource..
     *
     */
    public function testBrandLogoBrandItem()
    {
    }

    /**
     * Test case for callcsvreportCsvCallCsvReportItem
     *
     * Retrieves a CallCsvReport resource..
     *
     */
    public function testCallcsvreportCsvCallCsvReportItem()
    {
    }

    /**
     * Test case for deleteAdministratorItem
     *
     * Removes the Administrator resource..
     *
     */
    public function testDeleteAdministratorItem()
    {
    }

    /**
     * Test case for deleteBalanceNotificationItem
     *
     * Removes the BalanceNotification resource..
     *
     */
    public function testDeleteBalanceNotificationItem()
    {
    }

    /**
     * Test case for deleteBannedAddressItem
     *
     * Removes the BannedAddress resource..
     *
     */
    public function testDeleteBannedAddressItem()
    {
    }

    /**
     * Test case for deleteBrandServiceItem
     *
     * Removes the BrandService resource..
     *
     */
    public function testDeleteBrandServiceItem()
    {
    }

    /**
     * Test case for deleteCallCsvSchedulerItem
     *
     * Removes the CallCsvScheduler resource..
     *
     */
    public function testDeleteCallCsvSchedulerItem()
    {
    }

    /**
     * Test case for deleteCarrierItem
     *
     * Removes the Carrier resource..
     *
     */
    public function testDeleteCarrierItem()
    {
    }

    /**
     * Test case for deleteCarrierServerItem
     *
     * Removes the CarrierServer resource..
     *
     */
    public function testDeleteCarrierServerItem()
    {
    }

    /**
     * Test case for deleteCompanyItem
     *
     * Removes the Company resource..
     *
     */
    public function testDeleteCompanyItem()
    {
    }

    /**
     * Test case for deleteDdiItem
     *
     * Removes the Ddi resource..
     *
     */
    public function testDeleteDdiItem()
    {
    }

    /**
     * Test case for deleteDdiProviderAddressItem
     *
     * Removes the DdiProviderAddress resource..
     *
     */
    public function testDeleteDdiProviderAddressItem()
    {
    }

    /**
     * Test case for deleteDdiProviderItem
     *
     * Removes the DdiProvider resource..
     *
     */
    public function testDeleteDdiProviderItem()
    {
    }

    /**
     * Test case for deleteDdiProviderRegistrationItem
     *
     * Removes the DdiProviderRegistration resource..
     *
     */
    public function testDeleteDdiProviderRegistrationItem()
    {
    }

    /**
     * Test case for deleteDestinationItem
     *
     * Removes the Destination resource..
     *
     */
    public function testDeleteDestinationItem()
    {
    }

    /**
     * Test case for deleteDestinationRateGroupItem
     *
     * Removes the DestinationRateGroup resource..
     *
     */
    public function testDeleteDestinationRateGroupItem()
    {
    }

    /**
     * Test case for deleteDestinationRateItem
     *
     * Removes the DestinationRate resource..
     *
     */
    public function testDeleteDestinationRateItem()
    {
    }

    /**
     * Test case for deleteFeaturesRelCompanyItem
     *
     * Removes the FeaturesRelCompany resource..
     *
     */
    public function testDeleteFeaturesRelCompanyItem()
    {
    }

    /**
     * Test case for deleteFixedCostItem
     *
     * Removes the FixedCost resource..
     *
     */
    public function testDeleteFixedCostItem()
    {
    }

    /**
     * Test case for deleteFixedCostsRelInvoiceItem
     *
     * Removes the FixedCostsRelInvoice resource..
     *
     */
    public function testDeleteFixedCostsRelInvoiceItem()
    {
    }

    /**
     * Test case for deleteFixedCostsRelInvoiceSchedulerItem
     *
     * Removes the FixedCostsRelInvoiceScheduler resource..
     *
     */
    public function testDeleteFixedCostsRelInvoiceSchedulerItem()
    {
    }

    /**
     * Test case for deleteFriendItem
     *
     * Removes the Friend resource..
     *
     */
    public function testDeleteFriendItem()
    {
    }

    /**
     * Test case for deleteInvoiceItem
     *
     * Removes the Invoice resource..
     *
     */
    public function testDeleteInvoiceItem()
    {
    }

    /**
     * Test case for deleteInvoiceNumberSequenceItem
     *
     * Removes the InvoiceNumberSequence resource..
     *
     */
    public function testDeleteInvoiceNumberSequenceItem()
    {
    }

    /**
     * Test case for deleteInvoiceSchedulerItem
     *
     * Removes the InvoiceScheduler resource..
     *
     */
    public function testDeleteInvoiceSchedulerItem()
    {
    }

    /**
     * Test case for deleteInvoiceTemplateItem
     *
     * Removes the InvoiceTemplate resource..
     *
     */
    public function testDeleteInvoiceTemplateItem()
    {
    }

    /**
     * Test case for deleteNotificationTemplateContentItem
     *
     * Removes the NotificationTemplateContent resource..
     *
     */
    public function testDeleteNotificationTemplateContentItem()
    {
    }

    /**
     * Test case for deleteNotificationTemplateItem
     *
     * Removes the NotificationTemplate resource..
     *
     */
    public function testDeleteNotificationTemplateItem()
    {
    }

    /**
     * Test case for deleteOutgoingRoutingItem
     *
     * Removes the OutgoingRouting resource..
     *
     */
    public function testDeleteOutgoingRoutingItem()
    {
    }

    /**
     * Test case for deleteRatingPlanGroupItem
     *
     * Removes the RatingPlanGroup resource..
     *
     */
    public function testDeleteRatingPlanGroupItem()
    {
    }

    /**
     * Test case for deleteRatingPlanItem
     *
     * Removes the RatingPlan resource..
     *
     */
    public function testDeleteRatingPlanItem()
    {
    }

    /**
     * Test case for deleteRatingProfileItem
     *
     * Removes the RatingProfile resource..
     *
     */
    public function testDeleteRatingProfileItem()
    {
    }

    /**
     * Test case for deleteResidentialDeviceItem
     *
     * Removes the ResidentialDevice resource..
     *
     */
    public function testDeleteResidentialDeviceItem()
    {
    }

    /**
     * Test case for deleteRetailAccountItem
     *
     * Removes the RetailAccount resource..
     *
     */
    public function testDeleteRetailAccountItem()
    {
    }

    /**
     * Test case for deleteRoutingPatternGroupItem
     *
     * Removes the RoutingPatternGroup resource..
     *
     */
    public function testDeleteRoutingPatternGroupItem()
    {
    }

    /**
     * Test case for deleteRoutingPatternGroupsRelPatternItem
     *
     * Removes the RoutingPatternGroupsRelPattern resource..
     *
     */
    public function testDeleteRoutingPatternGroupsRelPatternItem()
    {
    }

    /**
     * Test case for deleteRoutingPatternItem
     *
     * Removes the RoutingPattern resource..
     *
     */
    public function testDeleteRoutingPatternItem()
    {
    }

    /**
     * Test case for deleteRoutingTagItem
     *
     * Removes the RoutingTag resource..
     *
     */
    public function testDeleteRoutingTagItem()
    {
    }

    /**
     * Test case for deleteSpecialNumberItem
     *
     * Removes the SpecialNumber resource..
     *
     */
    public function testDeleteSpecialNumberItem()
    {
    }

    /**
     * Test case for deleteTransformationRuleItem
     *
     * Removes the TransformationRule resource..
     *
     */
    public function testDeleteTransformationRuleItem()
    {
    }

    /**
     * Test case for deleteTransformationRuleSetItem
     *
     * Removes the TransformationRuleSet resource..
     *
     */
    public function testDeleteTransformationRuleSetItem()
    {
    }

    /**
     * Test case for deleteWebPortalItem
     *
     * Removes the WebPortal resource..
     *
     */
    public function testDeleteWebPortalItem()
    {
    }

    /**
     * Test case for destinationrategroupFileDestinationRateGroupItem
     *
     * Retrieves a DestinationRateGroup resource..
     *
     */
    public function testDestinationrategroupFileDestinationRateGroupItem()
    {
    }

    /**
     * Test case for getAdministratorCollection
     *
     * Retrieves the collection of Administrator resources..
     *
     */
    public function testGetAdministratorCollection()
    {
    }

    /**
     * Test case for getAdministratorItem
     *
     * Retrieves a Administrator resource..
     *
     */
    public function testGetAdministratorItem()
    {
    }

    /**
     * Test case for getAdministratorRelPublicEntityCollection
     *
     * Retrieves the collection of AdministratorRelPublicEntity resources..
     *
     */
    public function testGetAdministratorRelPublicEntityCollection()
    {
    }

    /**
     * Test case for getAdministratorRelPublicEntityItem
     *
     * Retrieves a AdministratorRelPublicEntity resource..
     *
     */
    public function testGetAdministratorRelPublicEntityItem()
    {
    }

    /**
     * Test case for getBalanceNotificationCollection
     *
     * Retrieves the collection of BalanceNotification resources..
     *
     */
    public function testGetBalanceNotificationCollection()
    {
    }

    /**
     * Test case for getBalanceNotificationItem
     *
     * Retrieves a BalanceNotification resource..
     *
     */
    public function testGetBalanceNotificationItem()
    {
    }

    /**
     * Test case for getBannedAddressCollection
     *
     * Retrieves the collection of BannedAddress resources..
     *
     */
    public function testGetBannedAddressCollection()
    {
    }

    /**
     * Test case for getBannedAddressItem
     *
     * Retrieves a BannedAddress resource..
     *
     */
    public function testGetBannedAddressItem()
    {
    }

    /**
     * Test case for getBillableCallCollection
     *
     * Retrieves the collection of BillableCall resources..
     *
     */
    public function testGetBillableCallCollection()
    {
    }

    /**
     * Test case for getBillableCallItem
     *
     * Retrieves a BillableCall resource..
     *
     */
    public function testGetBillableCallItem()
    {
    }

    /**
     * Test case for getBrandCollection
     *
     * Retrieves the collection of Brand resources..
     *
     */
    public function testGetBrandCollection()
    {
    }

    /**
     * Test case for getBrandItem
     *
     * Retrieves a Brand resource..
     *
     */
    public function testGetBrandItem()
    {
    }

    /**
     * Test case for getBrandServiceCollection
     *
     * Retrieves the collection of BrandService resources..
     *
     */
    public function testGetBrandServiceCollection()
    {
    }

    /**
     * Test case for getBrandServiceItem
     *
     * Retrieves a BrandService resource..
     *
     */
    public function testGetBrandServiceItem()
    {
    }

    /**
     * Test case for getCallCsvReportCollection
     *
     * Retrieves the collection of CallCsvReport resources..
     *
     */
    public function testGetCallCsvReportCollection()
    {
    }

    /**
     * Test case for getCallCsvReportItem
     *
     * Retrieves a CallCsvReport resource..
     *
     */
    public function testGetCallCsvReportItem()
    {
    }

    /**
     * Test case for getCallCsvSchedulerCollection
     *
     * Retrieves the collection of CallCsvScheduler resources..
     *
     */
    public function testGetCallCsvSchedulerCollection()
    {
    }

    /**
     * Test case for getCallCsvSchedulerItem
     *
     * Retrieves a CallCsvScheduler resource..
     *
     */
    public function testGetCallCsvSchedulerItem()
    {
    }

    /**
     * Test case for getCarrierCollection
     *
     * Retrieves the collection of Carrier resources..
     *
     */
    public function testGetCarrierCollection()
    {
    }

    /**
     * Test case for getCarrierItem
     *
     * Retrieves a Carrier resource..
     *
     */
    public function testGetCarrierItem()
    {
    }

    /**
     * Test case for getCarrierServerCollection
     *
     * Retrieves the collection of CarrierServer resources..
     *
     */
    public function testGetCarrierServerCollection()
    {
    }

    /**
     * Test case for getCarrierServerItem
     *
     * Retrieves a CarrierServer resource..
     *
     */
    public function testGetCarrierServerItem()
    {
    }

    /**
     * Test case for getCompanyCollection
     *
     * Retrieves the collection of Company resources..
     *
     */
    public function testGetCompanyCollection()
    {
    }

    /**
     * Test case for getCompanyItem
     *
     * Retrieves a Company resource..
     *
     */
    public function testGetCompanyItem()
    {
    }

    /**
     * Test case for getCountryCollection
     *
     * Retrieves the collection of Country resources..
     *
     */
    public function testGetCountryCollection()
    {
    }

    /**
     * Test case for getCountryItem
     *
     * Retrieves a Country resource..
     *
     */
    public function testGetCountryItem()
    {
    }

    /**
     * Test case for getCurrencyCollection
     *
     * Retrieves the collection of Currency resources..
     *
     */
    public function testGetCurrencyCollection()
    {
    }

    /**
     * Test case for getCurrencyItem
     *
     * Retrieves a Currency resource..
     *
     */
    public function testGetCurrencyItem()
    {
    }

    /**
     * Test case for getDdiCollection
     *
     * Retrieves the collection of Ddi resources..
     *
     */
    public function testGetDdiCollection()
    {
    }

    /**
     * Test case for getDdiItem
     *
     * Retrieves a Ddi resource..
     *
     */
    public function testGetDdiItem()
    {
    }

    /**
     * Test case for getDdiProviderAddressCollection
     *
     * Retrieves the collection of DdiProviderAddress resources..
     *
     */
    public function testGetDdiProviderAddressCollection()
    {
    }

    /**
     * Test case for getDdiProviderAddressItem
     *
     * Retrieves a DdiProviderAddress resource..
     *
     */
    public function testGetDdiProviderAddressItem()
    {
    }

    /**
     * Test case for getDdiProviderCollection
     *
     * Retrieves the collection of DdiProvider resources..
     *
     */
    public function testGetDdiProviderCollection()
    {
    }

    /**
     * Test case for getDdiProviderItem
     *
     * Retrieves a DdiProvider resource..
     *
     */
    public function testGetDdiProviderItem()
    {
    }

    /**
     * Test case for getDdiProviderRegistrationCollection
     *
     * Retrieves the collection of DdiProviderRegistration resources..
     *
     */
    public function testGetDdiProviderRegistrationCollection()
    {
    }

    /**
     * Test case for getDdiProviderRegistrationItem
     *
     * Retrieves a DdiProviderRegistration resource..
     *
     */
    public function testGetDdiProviderRegistrationItem()
    {
    }

    /**
     * Test case for getDestinationCollection
     *
     * Retrieves the collection of Destination resources..
     *
     */
    public function testGetDestinationCollection()
    {
    }

    /**
     * Test case for getDestinationItem
     *
     * Retrieves a Destination resource..
     *
     */
    public function testGetDestinationItem()
    {
    }

    /**
     * Test case for getDestinationRateCollection
     *
     * Retrieves the collection of DestinationRate resources..
     *
     */
    public function testGetDestinationRateCollection()
    {
    }

    /**
     * Test case for getDestinationRateGroupCollection
     *
     * Retrieves the collection of DestinationRateGroup resources..
     *
     */
    public function testGetDestinationRateGroupCollection()
    {
    }

    /**
     * Test case for getDestinationRateGroupItem
     *
     * Retrieves a DestinationRateGroup resource..
     *
     */
    public function testGetDestinationRateGroupItem()
    {
    }

    /**
     * Test case for getDestinationRateItem
     *
     * Retrieves a DestinationRate resource..
     *
     */
    public function testGetDestinationRateItem()
    {
    }

    /**
     * Test case for getFaxCollection
     *
     * Retrieves the collection of Fax resources..
     *
     */
    public function testGetFaxCollection()
    {
    }

    /**
     * Test case for getFeatureCollection
     *
     * Retrieves the collection of Feature resources..
     *
     */
    public function testGetFeatureCollection()
    {
    }

    /**
     * Test case for getFeatureItem
     *
     * Retrieves a Feature resource..
     *
     */
    public function testGetFeatureItem()
    {
    }

    /**
     * Test case for getFeaturesRelBrandCollection
     *
     * Retrieves the collection of FeaturesRelBrand resources..
     *
     */
    public function testGetFeaturesRelBrandCollection()
    {
    }

    /**
     * Test case for getFeaturesRelBrandItem
     *
     * Retrieves a FeaturesRelBrand resource..
     *
     */
    public function testGetFeaturesRelBrandItem()
    {
    }

    /**
     * Test case for getFeaturesRelCompanyCollection
     *
     * Retrieves the collection of FeaturesRelCompany resources..
     *
     */
    public function testGetFeaturesRelCompanyCollection()
    {
    }

    /**
     * Test case for getFeaturesRelCompanyItem
     *
     * Retrieves a FeaturesRelCompany resource..
     *
     */
    public function testGetFeaturesRelCompanyItem()
    {
    }

    /**
     * Test case for getFixedCostCollection
     *
     * Retrieves the collection of FixedCost resources..
     *
     */
    public function testGetFixedCostCollection()
    {
    }

    /**
     * Test case for getFixedCostItem
     *
     * Retrieves a FixedCost resource..
     *
     */
    public function testGetFixedCostItem()
    {
    }

    /**
     * Test case for getFixedCostsRelInvoiceCollection
     *
     * Retrieves the collection of FixedCostsRelInvoice resources..
     *
     */
    public function testGetFixedCostsRelInvoiceCollection()
    {
    }

    /**
     * Test case for getFixedCostsRelInvoiceItem
     *
     * Retrieves a FixedCostsRelInvoice resource..
     *
     */
    public function testGetFixedCostsRelInvoiceItem()
    {
    }

    /**
     * Test case for getFixedCostsRelInvoiceSchedulerCollection
     *
     * Retrieves the collection of FixedCostsRelInvoiceScheduler resources..
     *
     */
    public function testGetFixedCostsRelInvoiceSchedulerCollection()
    {
    }

    /**
     * Test case for getFixedCostsRelInvoiceSchedulerItem
     *
     * Retrieves a FixedCostsRelInvoiceScheduler resource..
     *
     */
    public function testGetFixedCostsRelInvoiceSchedulerItem()
    {
    }

    /**
     * Test case for getFriendCollection
     *
     * Retrieves the collection of Friend resources..
     *
     */
    public function testGetFriendCollection()
    {
    }

    /**
     * Test case for getFriendItem
     *
     * Retrieves a Friend resource..
     *
     */
    public function testGetFriendItem()
    {
    }

    /**
     * Test case for getInvoiceCollection
     *
     * Retrieves the collection of Invoice resources..
     *
     */
    public function testGetInvoiceCollection()
    {
    }

    /**
     * Test case for getInvoiceItem
     *
     * Retrieves a Invoice resource..
     *
     */
    public function testGetInvoiceItem()
    {
    }

    /**
     * Test case for getInvoiceNumberSequenceCollection
     *
     * Retrieves the collection of InvoiceNumberSequence resources..
     *
     */
    public function testGetInvoiceNumberSequenceCollection()
    {
    }

    /**
     * Test case for getInvoiceNumberSequenceItem
     *
     * Retrieves a InvoiceNumberSequence resource..
     *
     */
    public function testGetInvoiceNumberSequenceItem()
    {
    }

    /**
     * Test case for getInvoiceSchedulerCollection
     *
     * Retrieves the collection of InvoiceScheduler resources..
     *
     */
    public function testGetInvoiceSchedulerCollection()
    {
    }

    /**
     * Test case for getInvoiceSchedulerItem
     *
     * Retrieves a InvoiceScheduler resource..
     *
     */
    public function testGetInvoiceSchedulerItem()
    {
    }

    /**
     * Test case for getInvoiceTemplateCollection
     *
     * Retrieves the collection of InvoiceTemplate resources..
     *
     */
    public function testGetInvoiceTemplateCollection()
    {
    }

    /**
     * Test case for getInvoiceTemplateItem
     *
     * Retrieves a InvoiceTemplate resource..
     *
     */
    public function testGetInvoiceTemplateItem()
    {
    }

    /**
     * Test case for getLanguageCollection
     *
     * Retrieves the collection of Language resources..
     *
     */
    public function testGetLanguageCollection()
    {
    }

    /**
     * Test case for getLanguageItem
     *
     * Retrieves a Language resource..
     *
     */
    public function testGetLanguageItem()
    {
    }

    /**
     * Test case for getNotificationTemplateCollection
     *
     * Retrieves the collection of NotificationTemplate resources..
     *
     */
    public function testGetNotificationTemplateCollection()
    {
    }

    /**
     * Test case for getNotificationTemplateContentCollection
     *
     * Retrieves the collection of NotificationTemplateContent resources..
     *
     */
    public function testGetNotificationTemplateContentCollection()
    {
    }

    /**
     * Test case for getNotificationTemplateContentItem
     *
     * Retrieves a NotificationTemplateContent resource..
     *
     */
    public function testGetNotificationTemplateContentItem()
    {
    }

    /**
     * Test case for getNotificationTemplateItem
     *
     * Retrieves a NotificationTemplate resource..
     *
     */
    public function testGetNotificationTemplateItem()
    {
    }

    /**
     * Test case for getOutgoingRoutingCollection
     *
     * Retrieves the collection of OutgoingRouting resources..
     *
     */
    public function testGetOutgoingRoutingCollection()
    {
    }

    /**
     * Test case for getOutgoingRoutingItem
     *
     * Retrieves a OutgoingRouting resource..
     *
     */
    public function testGetOutgoingRoutingItem()
    {
    }

    /**
     * Test case for getProxyTrunkCollection
     *
     * Retrieves the collection of ProxyTrunk resources..
     *
     */
    public function testGetProxyTrunkCollection()
    {
    }

    /**
     * Test case for getProxyTrunkItem
     *
     * Retrieves a ProxyTrunk resource..
     *
     */
    public function testGetProxyTrunkItem()
    {
    }

    /**
     * Test case for getPublicEntityCollection
     *
     * Retrieves the collection of PublicEntity resources..
     *
     */
    public function testGetPublicEntityCollection()
    {
    }

    /**
     * Test case for getPublicEntityItem
     *
     * Retrieves a PublicEntity resource..
     *
     */
    public function testGetPublicEntityItem()
    {
    }

    /**
     * Test case for getRatingPlanCollection
     *
     * Retrieves the collection of RatingPlan resources..
     *
     */
    public function testGetRatingPlanCollection()
    {
    }

    /**
     * Test case for getRatingPlanGroupCollection
     *
     * Retrieves the collection of RatingPlanGroup resources..
     *
     */
    public function testGetRatingPlanGroupCollection()
    {
    }

    /**
     * Test case for getRatingPlanGroupItem
     *
     * Retrieves a RatingPlanGroup resource..
     *
     */
    public function testGetRatingPlanGroupItem()
    {
    }

    /**
     * Test case for getRatingPlanItem
     *
     * Retrieves a RatingPlan resource..
     *
     */
    public function testGetRatingPlanItem()
    {
    }

    /**
     * Test case for getRatingProfileCollection
     *
     * Retrieves the collection of RatingProfile resources..
     *
     */
    public function testGetRatingProfileCollection()
    {
    }

    /**
     * Test case for getRatingProfileItem
     *
     * Retrieves a RatingProfile resource..
     *
     */
    public function testGetRatingProfileItem()
    {
    }

    /**
     * Test case for getResidentialDeviceCollection
     *
     * Retrieves the collection of ResidentialDevice resources..
     *
     */
    public function testGetResidentialDeviceCollection()
    {
    }

    /**
     * Test case for getResidentialDeviceItem
     *
     * Retrieves a ResidentialDevice resource..
     *
     */
    public function testGetResidentialDeviceItem()
    {
    }

    /**
     * Test case for getRetailAccountCollection
     *
     * Retrieves the collection of RetailAccount resources..
     *
     */
    public function testGetRetailAccountCollection()
    {
    }

    /**
     * Test case for getRetailAccountItem
     *
     * Retrieves a RetailAccount resource..
     *
     */
    public function testGetRetailAccountItem()
    {
    }

    /**
     * Test case for getRoutingPatternCollection
     *
     * Retrieves the collection of RoutingPattern resources..
     *
     */
    public function testGetRoutingPatternCollection()
    {
    }

    /**
     * Test case for getRoutingPatternGroupCollection
     *
     * Retrieves the collection of RoutingPatternGroup resources..
     *
     */
    public function testGetRoutingPatternGroupCollection()
    {
    }

    /**
     * Test case for getRoutingPatternGroupItem
     *
     * Retrieves a RoutingPatternGroup resource..
     *
     */
    public function testGetRoutingPatternGroupItem()
    {
    }

    /**
     * Test case for getRoutingPatternGroupsRelPatternCollection
     *
     * Retrieves the collection of RoutingPatternGroupsRelPattern resources..
     *
     */
    public function testGetRoutingPatternGroupsRelPatternCollection()
    {
    }

    /**
     * Test case for getRoutingPatternGroupsRelPatternItem
     *
     * Retrieves a RoutingPatternGroupsRelPattern resource..
     *
     */
    public function testGetRoutingPatternGroupsRelPatternItem()
    {
    }

    /**
     * Test case for getRoutingPatternItem
     *
     * Retrieves a RoutingPattern resource..
     *
     */
    public function testGetRoutingPatternItem()
    {
    }

    /**
     * Test case for getRoutingTagCollection
     *
     * Retrieves the collection of RoutingTag resources..
     *
     */
    public function testGetRoutingTagCollection()
    {
    }

    /**
     * Test case for getRoutingTagItem
     *
     * Retrieves a RoutingTag resource..
     *
     */
    public function testGetRoutingTagItem()
    {
    }

    /**
     * Test case for getServiceCollection
     *
     * Retrieves the collection of Service resources..
     *
     */
    public function testGetServiceCollection()
    {
    }

    /**
     * Test case for getServiceItem
     *
     * Retrieves a Service resource..
     *
     */
    public function testGetServiceItem()
    {
    }

    /**
     * Test case for getSpecialNumberCollection
     *
     * Retrieves the collection of SpecialNumber resources..
     *
     */
    public function testGetSpecialNumberCollection()
    {
    }

    /**
     * Test case for getSpecialNumberItem
     *
     * Retrieves a SpecialNumber resource..
     *
     */
    public function testGetSpecialNumberItem()
    {
    }

    /**
     * Test case for getStatusCollectionFriendCollection
     *
     * Retrieves the collection of Friend resources..
     *
     */
    public function testGetStatusCollectionFriendCollection()
    {
    }

    /**
     * Test case for getStatusCollectionResidentialDeviceCollection
     *
     * Retrieves the collection of ResidentialDevice resources..
     *
     */
    public function testGetStatusCollectionResidentialDeviceCollection()
    {
    }

    /**
     * Test case for getStatusCollectionRetailAccountCollection
     *
     * Retrieves the collection of RetailAccount resources..
     *
     */
    public function testGetStatusCollectionRetailAccountCollection()
    {
    }

    /**
     * Test case for getStatusCollectionTerminalCollection
     *
     * Retrieves the collection of Terminal resources..
     *
     */
    public function testGetStatusCollectionTerminalCollection()
    {
    }

    /**
     * Test case for getTimezoneCollection
     *
     * Retrieves the collection of Timezone resources..
     *
     */
    public function testGetTimezoneCollection()
    {
    }

    /**
     * Test case for getTimezoneItem
     *
     * Retrieves a Timezone resource..
     *
     */
    public function testGetTimezoneItem()
    {
    }

    /**
     * Test case for getTransformationRuleCollection
     *
     * Retrieves the collection of TransformationRule resources..
     *
     */
    public function testGetTransformationRuleCollection()
    {
    }

    /**
     * Test case for getTransformationRuleItem
     *
     * Retrieves a TransformationRule resource..
     *
     */
    public function testGetTransformationRuleItem()
    {
    }

    /**
     * Test case for getTransformationRuleSetCollection
     *
     * Retrieves the collection of TransformationRuleSet resources..
     *
     */
    public function testGetTransformationRuleSetCollection()
    {
    }

    /**
     * Test case for getTransformationRuleSetItem
     *
     * Retrieves a TransformationRuleSet resource..
     *
     */
    public function testGetTransformationRuleSetItem()
    {
    }

    /**
     * Test case for getUserCollection
     *
     * Retrieves the collection of User resources..
     *
     */
    public function testGetUserCollection()
    {
    }

    /**
     * Test case for getWebPortalCollection
     *
     * Retrieves the collection of WebPortal resources..
     *
     */
    public function testGetWebPortalCollection()
    {
    }

    /**
     * Test case for getWebPortalItem
     *
     * Retrieves a WebPortal resource..
     *
     */
    public function testGetWebPortalItem()
    {
    }

    /**
     * Test case for invoicePdfInvoiceItem
     *
     * Retrieves a Invoice resource..
     *
     */
    public function testInvoicePdfInvoiceItem()
    {
    }

    /**
     * Test case for postAdministratorCollection
     *
     * Creates a Administrator resource..
     *
     */
    public function testPostAdministratorCollection()
    {
    }

    /**
     * Test case for postBalanceNotificationCollection
     *
     * Creates a BalanceNotification resource..
     *
     */
    public function testPostBalanceNotificationCollection()
    {
    }

    /**
     * Test case for postBrandServiceCollection
     *
     * Creates a BrandService resource..
     *
     */
    public function testPostBrandServiceCollection()
    {
    }

    /**
     * Test case for postCallCsvSchedulerCollection
     *
     * Creates a CallCsvScheduler resource..
     *
     */
    public function testPostCallCsvSchedulerCollection()
    {
    }

    /**
     * Test case for postCarrierCollection
     *
     * Creates a Carrier resource..
     *
     */
    public function testPostCarrierCollection()
    {
    }

    /**
     * Test case for postCarrierServerCollection
     *
     * Creates a CarrierServer resource..
     *
     */
    public function testPostCarrierServerCollection()
    {
    }

    /**
     * Test case for postCompanyCollection
     *
     * Creates a Company resource..
     *
     */
    public function testPostCompanyCollection()
    {
    }

    /**
     * Test case for postDdiCollection
     *
     * Creates a Ddi resource..
     *
     */
    public function testPostDdiCollection()
    {
    }

    /**
     * Test case for postDdiProviderAddressCollection
     *
     * Creates a DdiProviderAddress resource..
     *
     */
    public function testPostDdiProviderAddressCollection()
    {
    }

    /**
     * Test case for postDdiProviderCollection
     *
     * Creates a DdiProvider resource..
     *
     */
    public function testPostDdiProviderCollection()
    {
    }

    /**
     * Test case for postDdiProviderRegistrationCollection
     *
     * Creates a DdiProviderRegistration resource..
     *
     */
    public function testPostDdiProviderRegistrationCollection()
    {
    }

    /**
     * Test case for postDestinationCollection
     *
     * Creates a Destination resource..
     *
     */
    public function testPostDestinationCollection()
    {
    }

    /**
     * Test case for postDestinationRateCollection
     *
     * Creates a DestinationRate resource..
     *
     */
    public function testPostDestinationRateCollection()
    {
    }

    /**
     * Test case for postDestinationRateGroupCollection
     *
     * Creates a DestinationRateGroup resource..
     *
     */
    public function testPostDestinationRateGroupCollection()
    {
    }

    /**
     * Test case for postFeaturesRelCompanyCollection
     *
     * Creates a FeaturesRelCompany resource..
     *
     */
    public function testPostFeaturesRelCompanyCollection()
    {
    }

    /**
     * Test case for postFixedCostCollection
     *
     * Creates a FixedCost resource..
     *
     */
    public function testPostFixedCostCollection()
    {
    }

    /**
     * Test case for postFixedCostsRelInvoiceCollection
     *
     * Creates a FixedCostsRelInvoice resource..
     *
     */
    public function testPostFixedCostsRelInvoiceCollection()
    {
    }

    /**
     * Test case for postFixedCostsRelInvoiceSchedulerCollection
     *
     * Creates a FixedCostsRelInvoiceScheduler resource..
     *
     */
    public function testPostFixedCostsRelInvoiceSchedulerCollection()
    {
    }

    /**
     * Test case for postFriendCollection
     *
     * Creates a Friend resource..
     *
     */
    public function testPostFriendCollection()
    {
    }

    /**
     * Test case for postInvoiceCollection
     *
     * Creates a Invoice resource..
     *
     */
    public function testPostInvoiceCollection()
    {
    }

    /**
     * Test case for postInvoiceNumberSequenceCollection
     *
     * Creates a InvoiceNumberSequence resource..
     *
     */
    public function testPostInvoiceNumberSequenceCollection()
    {
    }

    /**
     * Test case for postInvoiceSchedulerCollection
     *
     * Creates a InvoiceScheduler resource..
     *
     */
    public function testPostInvoiceSchedulerCollection()
    {
    }

    /**
     * Test case for postInvoiceTemplateCollection
     *
     * Creates a InvoiceTemplate resource..
     *
     */
    public function testPostInvoiceTemplateCollection()
    {
    }

    /**
     * Test case for postNotificationTemplateCollection
     *
     * Creates a NotificationTemplate resource..
     *
     */
    public function testPostNotificationTemplateCollection()
    {
    }

    /**
     * Test case for postNotificationTemplateContentCollection
     *
     * Creates a NotificationTemplateContent resource..
     *
     */
    public function testPostNotificationTemplateContentCollection()
    {
    }

    /**
     * Test case for postOutgoingRoutingCollection
     *
     * Creates a OutgoingRouting resource..
     *
     */
    public function testPostOutgoingRoutingCollection()
    {
    }

    /**
     * Test case for postRatingPlanCollection
     *
     * Creates a RatingPlan resource..
     *
     */
    public function testPostRatingPlanCollection()
    {
    }

    /**
     * Test case for postRatingPlanGroupCollection
     *
     * Creates a RatingPlanGroup resource..
     *
     */
    public function testPostRatingPlanGroupCollection()
    {
    }

    /**
     * Test case for postRatingProfileCollection
     *
     * Creates a RatingProfile resource..
     *
     */
    public function testPostRatingProfileCollection()
    {
    }

    /**
     * Test case for postResidentialDeviceCollection
     *
     * Creates a ResidentialDevice resource..
     *
     */
    public function testPostResidentialDeviceCollection()
    {
    }

    /**
     * Test case for postRetailAccountCollection
     *
     * Creates a RetailAccount resource..
     *
     */
    public function testPostRetailAccountCollection()
    {
    }

    /**
     * Test case for postRoutingPatternCollection
     *
     * Creates a RoutingPattern resource..
     *
     */
    public function testPostRoutingPatternCollection()
    {
    }

    /**
     * Test case for postRoutingPatternGroupCollection
     *
     * Creates a RoutingPatternGroup resource..
     *
     */
    public function testPostRoutingPatternGroupCollection()
    {
    }

    /**
     * Test case for postRoutingPatternGroupsRelPatternCollection
     *
     * Creates a RoutingPatternGroupsRelPattern resource..
     *
     */
    public function testPostRoutingPatternGroupsRelPatternCollection()
    {
    }

    /**
     * Test case for postRoutingTagCollection
     *
     * Creates a RoutingTag resource..
     *
     */
    public function testPostRoutingTagCollection()
    {
    }

    /**
     * Test case for postSpecialNumberCollection
     *
     * Creates a SpecialNumber resource..
     *
     */
    public function testPostSpecialNumberCollection()
    {
    }

    /**
     * Test case for postTransformationRuleCollection
     *
     * Creates a TransformationRule resource..
     *
     */
    public function testPostTransformationRuleCollection()
    {
    }

    /**
     * Test case for postTransformationRuleSetCollection
     *
     * Creates a TransformationRuleSet resource..
     *
     */
    public function testPostTransformationRuleSetCollection()
    {
    }

    /**
     * Test case for postUsersMassImportUsersMassImportCollection
     *
     * Creates a UsersMassImport resource..
     *
     */
    public function testPostUsersMassImportUsersMassImportCollection()
    {
    }

    /**
     * Test case for postWebPortalCollection
     *
     * Creates a WebPortal resource..
     *
     */
    public function testPostWebPortalCollection()
    {
    }

    /**
     * Test case for putAdministratorItem
     *
     * Replaces the Administrator resource..
     *
     */
    public function testPutAdministratorItem()
    {
    }

    /**
     * Test case for putAdministratorRelPublicEntityItem
     *
     * Replaces the AdministratorRelPublicEntity resource..
     *
     */
    public function testPutAdministratorRelPublicEntityItem()
    {
    }

    /**
     * Test case for putBalanceNotificationItem
     *
     * Replaces the BalanceNotification resource..
     *
     */
    public function testPutBalanceNotificationItem()
    {
    }

    /**
     * Test case for putBillableCallRateByCallidBillableCallItem
     *
     * Replaces the BillableCall resource..
     *
     */
    public function testPutBillableCallRateByCallidBillableCallItem()
    {
    }

    /**
     * Test case for putBrandItem
     *
     * Replaces the Brand resource..
     *
     */
    public function testPutBrandItem()
    {
    }

    /**
     * Test case for putBrandServiceItem
     *
     * Replaces the BrandService resource..
     *
     */
    public function testPutBrandServiceItem()
    {
    }

    /**
     * Test case for putCallCsvSchedulerItem
     *
     * Replaces the CallCsvScheduler resource..
     *
     */
    public function testPutCallCsvSchedulerItem()
    {
    }

    /**
     * Test case for putCarrierItem
     *
     * Replaces the Carrier resource..
     *
     */
    public function testPutCarrierItem()
    {
    }

    /**
     * Test case for putCarrierServerItem
     *
     * Replaces the CarrierServer resource..
     *
     */
    public function testPutCarrierServerItem()
    {
    }

    /**
     * Test case for putCompanyItem
     *
     * Replaces the Company resource..
     *
     */
    public function testPutCompanyItem()
    {
    }

    /**
     * Test case for putDdiItem
     *
     * Replaces the Ddi resource..
     *
     */
    public function testPutDdiItem()
    {
    }

    /**
     * Test case for putDdiProviderAddressItem
     *
     * Replaces the DdiProviderAddress resource..
     *
     */
    public function testPutDdiProviderAddressItem()
    {
    }

    /**
     * Test case for putDdiProviderItem
     *
     * Replaces the DdiProvider resource..
     *
     */
    public function testPutDdiProviderItem()
    {
    }

    /**
     * Test case for putDdiProviderRegistrationItem
     *
     * Replaces the DdiProviderRegistration resource..
     *
     */
    public function testPutDdiProviderRegistrationItem()
    {
    }

    /**
     * Test case for putDestinationItem
     *
     * Replaces the Destination resource..
     *
     */
    public function testPutDestinationItem()
    {
    }

    /**
     * Test case for putDestinationRateGroupItem
     *
     * Replaces the DestinationRateGroup resource..
     *
     */
    public function testPutDestinationRateGroupItem()
    {
    }

    /**
     * Test case for putDestinationRateItem
     *
     * Replaces the DestinationRate resource..
     *
     */
    public function testPutDestinationRateItem()
    {
    }

    /**
     * Test case for putFixedCostItem
     *
     * Replaces the FixedCost resource..
     *
     */
    public function testPutFixedCostItem()
    {
    }

    /**
     * Test case for putFixedCostsRelInvoiceItem
     *
     * Replaces the FixedCostsRelInvoice resource..
     *
     */
    public function testPutFixedCostsRelInvoiceItem()
    {
    }

    /**
     * Test case for putFixedCostsRelInvoiceSchedulerItem
     *
     * Replaces the FixedCostsRelInvoiceScheduler resource..
     *
     */
    public function testPutFixedCostsRelInvoiceSchedulerItem()
    {
    }

    /**
     * Test case for putFriendItem
     *
     * Replaces the Friend resource..
     *
     */
    public function testPutFriendItem()
    {
    }

    /**
     * Test case for putInvoiceItem
     *
     * Replaces the Invoice resource..
     *
     */
    public function testPutInvoiceItem()
    {
    }

    /**
     * Test case for putInvoiceNumberSequenceItem
     *
     * Replaces the InvoiceNumberSequence resource..
     *
     */
    public function testPutInvoiceNumberSequenceItem()
    {
    }

    /**
     * Test case for putInvoiceSchedulerItem
     *
     * Replaces the InvoiceScheduler resource..
     *
     */
    public function testPutInvoiceSchedulerItem()
    {
    }

    /**
     * Test case for putInvoiceTemplateItem
     *
     * Replaces the InvoiceTemplate resource..
     *
     */
    public function testPutInvoiceTemplateItem()
    {
    }

    /**
     * Test case for putNotificationTemplateContentItem
     *
     * Replaces the NotificationTemplateContent resource..
     *
     */
    public function testPutNotificationTemplateContentItem()
    {
    }

    /**
     * Test case for putNotificationTemplateItem
     *
     * Replaces the NotificationTemplate resource..
     *
     */
    public function testPutNotificationTemplateItem()
    {
    }

    /**
     * Test case for putOutgoingRoutingItem
     *
     * Replaces the OutgoingRouting resource..
     *
     */
    public function testPutOutgoingRoutingItem()
    {
    }

    /**
     * Test case for putRatingPlanGroupItem
     *
     * Replaces the RatingPlanGroup resource..
     *
     */
    public function testPutRatingPlanGroupItem()
    {
    }

    /**
     * Test case for putRatingPlanItem
     *
     * Replaces the RatingPlan resource..
     *
     */
    public function testPutRatingPlanItem()
    {
    }

    /**
     * Test case for putRatingProfileItem
     *
     * Replaces the RatingProfile resource..
     *
     */
    public function testPutRatingProfileItem()
    {
    }

    /**
     * Test case for putResidentialDeviceItem
     *
     * Replaces the ResidentialDevice resource..
     *
     */
    public function testPutResidentialDeviceItem()
    {
    }

    /**
     * Test case for putRetailAccountItem
     *
     * Replaces the RetailAccount resource..
     *
     */
    public function testPutRetailAccountItem()
    {
    }

    /**
     * Test case for putRoutingPatternGroupItem
     *
     * Replaces the RoutingPatternGroup resource..
     *
     */
    public function testPutRoutingPatternGroupItem()
    {
    }

    /**
     * Test case for putRoutingPatternGroupsRelPatternItem
     *
     * Replaces the RoutingPatternGroupsRelPattern resource..
     *
     */
    public function testPutRoutingPatternGroupsRelPatternItem()
    {
    }

    /**
     * Test case for putRoutingPatternItem
     *
     * Replaces the RoutingPattern resource..
     *
     */
    public function testPutRoutingPatternItem()
    {
    }

    /**
     * Test case for putRoutingTagItem
     *
     * Replaces the RoutingTag resource..
     *
     */
    public function testPutRoutingTagItem()
    {
    }

    /**
     * Test case for putSpecialNumberItem
     *
     * Replaces the SpecialNumber resource..
     *
     */
    public function testPutSpecialNumberItem()
    {
    }

    /**
     * Test case for putTransformationRuleItem
     *
     * Replaces the TransformationRule resource..
     *
     */
    public function testPutTransformationRuleItem()
    {
    }

    /**
     * Test case for putTransformationRuleSetItem
     *
     * Replaces the TransformationRuleSet resource..
     *
     */
    public function testPutTransformationRuleSetItem()
    {
    }

    /**
     * Test case for putWebPortalItem
     *
     * Replaces the WebPortal resource..
     *
     */
    public function testPutWebPortalItem()
    {
    }

    /**
     * Test case for webportalLogoWebPortalItem
     *
     * Retrieves a WebPortal resource..
     *
     */
    public function testWebportalLogoWebPortalItem()
    {
    }
}
