<?php
/**
 * Company
 *
 * PHP version 5
 *
 * @category Class
 * @package  Delta\Voip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Brand REST API
 *
 * OpenAPI spec version: 2.17.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Delta\Voip\Model;

use \ArrayAccess;
use \Delta\Voip\ObjectSerializer;

/**
 * Company Class Doc Comment
 *
 * @category Class
 * @package  Delta\Voip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Company implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Company';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'type' => 'string',
        'name' => 'string',
        'domain_users' => 'string',
        'nif' => 'string',
        'max_calls' => 'int',
        'max_daily_usage' => 'int',
        'max_daily_usage_email' => 'string',
        'postal_address' => 'string',
        'postal_code' => 'string',
        'town' => 'string',
        'province' => 'string',
        'country_name' => 'string',
        'ipfilter' => 'bool',
        'on_demand_record' => 'int',
        'on_demand_record_code' => 'string',
        'externallyextraopts' => 'string',
        'billing_method' => 'string',
        'balance' => 'float',
        'show_invoices' => 'bool',
        'id' => 'int',
        'language' => 'int',
        'default_timezone' => 'int',
        'country' => 'int',
        'currency' => 'int',
        'transformation_rule_set' => 'int',
        'outgoing_ddi' => 'int',
        'voicemail_notification_template' => 'int',
        'fax_notification_template' => 'int',
        'invoice_notification_template' => 'int',
        'call_csv_notification_template' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'type' => null,
        'name' => null,
        'domain_users' => null,
        'nif' => null,
        'max_calls' => null,
        'max_daily_usage' => null,
        'max_daily_usage_email' => null,
        'postal_address' => null,
        'postal_code' => null,
        'town' => null,
        'province' => null,
        'country_name' => null,
        'ipfilter' => null,
        'on_demand_record' => null,
        'on_demand_record_code' => null,
        'externallyextraopts' => null,
        'billing_method' => null,
        'balance' => 'float',
        'show_invoices' => null,
        'id' => null,
        'language' => null,
        'default_timezone' => null,
        'country' => null,
        'currency' => null,
        'transformation_rule_set' => null,
        'outgoing_ddi' => null,
        'voicemail_notification_template' => null,
        'fax_notification_template' => null,
        'invoice_notification_template' => null,
        'call_csv_notification_template' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'name' => 'name',
        'domain_users' => 'domainUsers',
        'nif' => 'nif',
        'max_calls' => 'maxCalls',
        'max_daily_usage' => 'maxDailyUsage',
        'max_daily_usage_email' => 'maxDailyUsageEmail',
        'postal_address' => 'postalAddress',
        'postal_code' => 'postalCode',
        'town' => 'town',
        'province' => 'province',
        'country_name' => 'countryName',
        'ipfilter' => 'ipfilter',
        'on_demand_record' => 'onDemandRecord',
        'on_demand_record_code' => 'onDemandRecordCode',
        'externallyextraopts' => 'externallyextraopts',
        'billing_method' => 'billingMethod',
        'balance' => 'balance',
        'show_invoices' => 'showInvoices',
        'id' => 'id',
        'language' => 'language',
        'default_timezone' => 'defaultTimezone',
        'country' => 'country',
        'currency' => 'currency',
        'transformation_rule_set' => 'transformationRuleSet',
        'outgoing_ddi' => 'outgoingDdi',
        'voicemail_notification_template' => 'voicemailNotificationTemplate',
        'fax_notification_template' => 'faxNotificationTemplate',
        'invoice_notification_template' => 'invoiceNotificationTemplate',
        'call_csv_notification_template' => 'callCsvNotificationTemplate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'name' => 'setName',
        'domain_users' => 'setDomainUsers',
        'nif' => 'setNif',
        'max_calls' => 'setMaxCalls',
        'max_daily_usage' => 'setMaxDailyUsage',
        'max_daily_usage_email' => 'setMaxDailyUsageEmail',
        'postal_address' => 'setPostalAddress',
        'postal_code' => 'setPostalCode',
        'town' => 'setTown',
        'province' => 'setProvince',
        'country_name' => 'setCountryName',
        'ipfilter' => 'setIpfilter',
        'on_demand_record' => 'setOnDemandRecord',
        'on_demand_record_code' => 'setOnDemandRecordCode',
        'externallyextraopts' => 'setExternallyextraopts',
        'billing_method' => 'setBillingMethod',
        'balance' => 'setBalance',
        'show_invoices' => 'setShowInvoices',
        'id' => 'setId',
        'language' => 'setLanguage',
        'default_timezone' => 'setDefaultTimezone',
        'country' => 'setCountry',
        'currency' => 'setCurrency',
        'transformation_rule_set' => 'setTransformationRuleSet',
        'outgoing_ddi' => 'setOutgoingDdi',
        'voicemail_notification_template' => 'setVoicemailNotificationTemplate',
        'fax_notification_template' => 'setFaxNotificationTemplate',
        'invoice_notification_template' => 'setInvoiceNotificationTemplate',
        'call_csv_notification_template' => 'setCallCsvNotificationTemplate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'name' => 'getName',
        'domain_users' => 'getDomainUsers',
        'nif' => 'getNif',
        'max_calls' => 'getMaxCalls',
        'max_daily_usage' => 'getMaxDailyUsage',
        'max_daily_usage_email' => 'getMaxDailyUsageEmail',
        'postal_address' => 'getPostalAddress',
        'postal_code' => 'getPostalCode',
        'town' => 'getTown',
        'province' => 'getProvince',
        'country_name' => 'getCountryName',
        'ipfilter' => 'getIpfilter',
        'on_demand_record' => 'getOnDemandRecord',
        'on_demand_record_code' => 'getOnDemandRecordCode',
        'externallyextraopts' => 'getExternallyextraopts',
        'billing_method' => 'getBillingMethod',
        'balance' => 'getBalance',
        'show_invoices' => 'getShowInvoices',
        'id' => 'getId',
        'language' => 'getLanguage',
        'default_timezone' => 'getDefaultTimezone',
        'country' => 'getCountry',
        'currency' => 'getCurrency',
        'transformation_rule_set' => 'getTransformationRuleSet',
        'outgoing_ddi' => 'getOutgoingDdi',
        'voicemail_notification_template' => 'getVoicemailNotificationTemplate',
        'fax_notification_template' => 'getFaxNotificationTemplate',
        'invoice_notification_template' => 'getInvoiceNotificationTemplate',
        'call_csv_notification_template' => 'getCallCsvNotificationTemplate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const TYPE_VPBX = 'vpbx';
    const TYPE_RETAIL = 'retail';
    const TYPE_WHOLESALE = 'wholesale';
    const TYPE_RESIDENTIAL = 'residential';
    const BILLING_METHOD_POSTPAID = 'postpaid';
    const BILLING_METHOD_PREPAID = 'prepaid';
    const BILLING_METHOD_PSEUDOPREPAID = 'pseudoprepaid';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_VPBX,
            self::TYPE_RETAIL,
            self::TYPE_WHOLESALE,
            self::TYPE_RESIDENTIAL,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBillingMethodAllowableValues()
    {
        return [
            self::BILLING_METHOD_POSTPAID,
            self::BILLING_METHOD_PREPAID,
            self::BILLING_METHOD_PSEUDOPREPAID,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['type'] = isset($data['type']) ? $data['type'] : 'vpbx';
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['domain_users'] = isset($data['domain_users']) ? $data['domain_users'] : null;
        $this->container['nif'] = isset($data['nif']) ? $data['nif'] : null;
        $this->container['max_calls'] = isset($data['max_calls']) ? $data['max_calls'] : null;
        $this->container['max_daily_usage'] = isset($data['max_daily_usage']) ? $data['max_daily_usage'] : null;
        $this->container['max_daily_usage_email'] = isset($data['max_daily_usage_email']) ? $data['max_daily_usage_email'] : null;
        $this->container['postal_address'] = isset($data['postal_address']) ? $data['postal_address'] : null;
        $this->container['postal_code'] = isset($data['postal_code']) ? $data['postal_code'] : null;
        $this->container['town'] = isset($data['town']) ? $data['town'] : null;
        $this->container['province'] = isset($data['province']) ? $data['province'] : null;
        $this->container['country_name'] = isset($data['country_name']) ? $data['country_name'] : null;
        $this->container['ipfilter'] = isset($data['ipfilter']) ? $data['ipfilter'] : false;
        $this->container['on_demand_record'] = isset($data['on_demand_record']) ? $data['on_demand_record'] : null;
        $this->container['on_demand_record_code'] = isset($data['on_demand_record_code']) ? $data['on_demand_record_code'] : null;
        $this->container['externallyextraopts'] = isset($data['externallyextraopts']) ? $data['externallyextraopts'] : null;
        $this->container['billing_method'] = isset($data['billing_method']) ? $data['billing_method'] : 'postpaid';
        $this->container['balance'] = isset($data['balance']) ? $data['balance'] : 0.0;
        $this->container['show_invoices'] = isset($data['show_invoices']) ? $data['show_invoices'] : false;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['language'] = isset($data['language']) ? $data['language'] : null;
        $this->container['default_timezone'] = isset($data['default_timezone']) ? $data['default_timezone'] : null;
        $this->container['country'] = isset($data['country']) ? $data['country'] : null;
        $this->container['currency'] = isset($data['currency']) ? $data['currency'] : null;
        $this->container['transformation_rule_set'] = isset($data['transformation_rule_set']) ? $data['transformation_rule_set'] : null;
        $this->container['outgoing_ddi'] = isset($data['outgoing_ddi']) ? $data['outgoing_ddi'] : null;
        $this->container['voicemail_notification_template'] = isset($data['voicemail_notification_template']) ? $data['voicemail_notification_template'] : null;
        $this->container['fax_notification_template'] = isset($data['fax_notification_template']) ? $data['fax_notification_template'] : null;
        $this->container['invoice_notification_template'] = isset($data['invoice_notification_template']) ? $data['invoice_notification_template'] : null;
        $this->container['call_csv_notification_template'] = isset($data['call_csv_notification_template']) ? $data['call_csv_notification_template'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ((mb_strlen($this->container['type']) > 25)) {
            $invalidProperties[] = "invalid value for 'type', the character length must be smaller than or equal to 25.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 80)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 80.";
        }

        if (!is_null($this->container['domain_users']) && (mb_strlen($this->container['domain_users']) > 190)) {
            $invalidProperties[] = "invalid value for 'domain_users', the character length must be smaller than or equal to 190.";
        }

        if ($this->container['nif'] === null) {
            $invalidProperties[] = "'nif' can't be null";
        }
        if ((mb_strlen($this->container['nif']) > 25)) {
            $invalidProperties[] = "invalid value for 'nif', the character length must be smaller than or equal to 25.";
        }

        if ($this->container['max_calls'] === null) {
            $invalidProperties[] = "'max_calls' can't be null";
        }
        if (($this->container['max_calls'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_calls', must be bigger than or equal to 0.";
        }

        if ($this->container['max_daily_usage'] === null) {
            $invalidProperties[] = "'max_daily_usage' can't be null";
        }
        if (($this->container['max_daily_usage'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_daily_usage', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['max_daily_usage_email']) && (mb_strlen($this->container['max_daily_usage_email']) > 100)) {
            $invalidProperties[] = "invalid value for 'max_daily_usage_email', the character length must be smaller than or equal to 100.";
        }

        if ($this->container['postal_address'] === null) {
            $invalidProperties[] = "'postal_address' can't be null";
        }
        if ((mb_strlen($this->container['postal_address']) > 255)) {
            $invalidProperties[] = "invalid value for 'postal_address', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['postal_code'] === null) {
            $invalidProperties[] = "'postal_code' can't be null";
        }
        if ((mb_strlen($this->container['postal_code']) > 10)) {
            $invalidProperties[] = "invalid value for 'postal_code', the character length must be smaller than or equal to 10.";
        }

        if ($this->container['town'] === null) {
            $invalidProperties[] = "'town' can't be null";
        }
        if ((mb_strlen($this->container['town']) > 255)) {
            $invalidProperties[] = "invalid value for 'town', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['province'] === null) {
            $invalidProperties[] = "'province' can't be null";
        }
        if ((mb_strlen($this->container['province']) > 255)) {
            $invalidProperties[] = "invalid value for 'province', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['country_name'] === null) {
            $invalidProperties[] = "'country_name' can't be null";
        }
        if ((mb_strlen($this->container['country_name']) > 255)) {
            $invalidProperties[] = "invalid value for 'country_name', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['on_demand_record_code']) && (mb_strlen($this->container['on_demand_record_code']) > 3)) {
            $invalidProperties[] = "invalid value for 'on_demand_record_code', the character length must be smaller than or equal to 3.";
        }

        if (!is_null($this->container['externallyextraopts']) && (mb_strlen($this->container['externallyextraopts']) > 65535)) {
            $invalidProperties[] = "invalid value for 'externallyextraopts', the character length must be smaller than or equal to 65535.";
        }

        if ($this->container['billing_method'] === null) {
            $invalidProperties[] = "'billing_method' can't be null";
        }
        $allowedValues = $this->getBillingMethodAllowableValues();
        if (!is_null($this->container['billing_method']) && !in_array($this->container['billing_method'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'billing_method', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ((mb_strlen($this->container['billing_method']) > 25)) {
            $invalidProperties[] = "invalid value for 'billing_method', the character length must be smaller than or equal to 25.";
        }

        if ($this->container['country'] === null) {
            $invalidProperties[] = "'country' can't be null";
        }
        if ($this->container['transformation_rule_set'] === null) {
            $invalidProperties[] = "'transformation_rule_set' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type 
     *
     * @return $this
     */
    public function setType($type)
    {
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        if ((mb_strlen($type) > 25)) {
            throw new \InvalidArgumentException('invalid length for $type when calling Company., must be smaller than or equal to 25.');
        }

        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name 
     *
     * @return $this
     */
    public function setName($name)
    {
        if ((mb_strlen($name) > 80)) {
            throw new \InvalidArgumentException('invalid length for $name when calling Company., must be smaller than or equal to 80.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets domain_users
     *
     * @return string
     */
    public function getDomainUsers()
    {
        return $this->container['domain_users'];
    }

    /**
     * Sets domain_users
     *
     * @param string $domain_users 
     *
     * @return $this
     */
    public function setDomainUsers($domain_users)
    {
        if (!is_null($domain_users) && (mb_strlen($domain_users) > 190)) {
            throw new \InvalidArgumentException('invalid length for $domain_users when calling Company., must be smaller than or equal to 190.');
        }

        $this->container['domain_users'] = $domain_users;

        return $this;
    }

    /**
     * Gets nif
     *
     * @return string
     */
    public function getNif()
    {
        return $this->container['nif'];
    }

    /**
     * Sets nif
     *
     * @param string $nif 
     *
     * @return $this
     */
    public function setNif($nif)
    {
        if ((mb_strlen($nif) > 25)) {
            throw new \InvalidArgumentException('invalid length for $nif when calling Company., must be smaller than or equal to 25.');
        }

        $this->container['nif'] = $nif;

        return $this;
    }

    /**
     * Gets max_calls
     *
     * @return int
     */
    public function getMaxCalls()
    {
        return $this->container['max_calls'];
    }

    /**
     * Sets max_calls
     *
     * @param int $max_calls 
     *
     * @return $this
     */
    public function setMaxCalls($max_calls)
    {

        if (($max_calls < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_calls when calling Company., must be bigger than or equal to 0.');
        }

        $this->container['max_calls'] = $max_calls;

        return $this;
    }

    /**
     * Gets max_daily_usage
     *
     * @return int
     */
    public function getMaxDailyUsage()
    {
        return $this->container['max_daily_usage'];
    }

    /**
     * Sets max_daily_usage
     *
     * @param int $max_daily_usage 
     *
     * @return $this
     */
    public function setMaxDailyUsage($max_daily_usage)
    {

        if (($max_daily_usage < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_daily_usage when calling Company., must be bigger than or equal to 0.');
        }

        $this->container['max_daily_usage'] = $max_daily_usage;

        return $this;
    }

    /**
     * Gets max_daily_usage_email
     *
     * @return string
     */
    public function getMaxDailyUsageEmail()
    {
        return $this->container['max_daily_usage_email'];
    }

    /**
     * Sets max_daily_usage_email
     *
     * @param string $max_daily_usage_email 
     *
     * @return $this
     */
    public function setMaxDailyUsageEmail($max_daily_usage_email)
    {
        if (!is_null($max_daily_usage_email) && (mb_strlen($max_daily_usage_email) > 100)) {
            throw new \InvalidArgumentException('invalid length for $max_daily_usage_email when calling Company., must be smaller than or equal to 100.');
        }

        $this->container['max_daily_usage_email'] = $max_daily_usage_email;

        return $this;
    }

    /**
     * Gets postal_address
     *
     * @return string
     */
    public function getPostalAddress()
    {
        return $this->container['postal_address'];
    }

    /**
     * Sets postal_address
     *
     * @param string $postal_address 
     *
     * @return $this
     */
    public function setPostalAddress($postal_address)
    {
        if ((mb_strlen($postal_address) > 255)) {
            throw new \InvalidArgumentException('invalid length for $postal_address when calling Company., must be smaller than or equal to 255.');
        }

        $this->container['postal_address'] = $postal_address;

        return $this;
    }

    /**
     * Gets postal_code
     *
     * @return string
     */
    public function getPostalCode()
    {
        return $this->container['postal_code'];
    }

    /**
     * Sets postal_code
     *
     * @param string $postal_code 
     *
     * @return $this
     */
    public function setPostalCode($postal_code)
    {
        if ((mb_strlen($postal_code) > 10)) {
            throw new \InvalidArgumentException('invalid length for $postal_code when calling Company., must be smaller than or equal to 10.');
        }

        $this->container['postal_code'] = $postal_code;

        return $this;
    }

    /**
     * Gets town
     *
     * @return string
     */
    public function getTown()
    {
        return $this->container['town'];
    }

    /**
     * Sets town
     *
     * @param string $town 
     *
     * @return $this
     */
    public function setTown($town)
    {
        if ((mb_strlen($town) > 255)) {
            throw new \InvalidArgumentException('invalid length for $town when calling Company., must be smaller than or equal to 255.');
        }

        $this->container['town'] = $town;

        return $this;
    }

    /**
     * Gets province
     *
     * @return string
     */
    public function getProvince()
    {
        return $this->container['province'];
    }

    /**
     * Sets province
     *
     * @param string $province 
     *
     * @return $this
     */
    public function setProvince($province)
    {
        if ((mb_strlen($province) > 255)) {
            throw new \InvalidArgumentException('invalid length for $province when calling Company., must be smaller than or equal to 255.');
        }

        $this->container['province'] = $province;

        return $this;
    }

    /**
     * Gets country_name
     *
     * @return string
     */
    public function getCountryName()
    {
        return $this->container['country_name'];
    }

    /**
     * Sets country_name
     *
     * @param string $country_name 
     *
     * @return $this
     */
    public function setCountryName($country_name)
    {
        if ((mb_strlen($country_name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $country_name when calling Company., must be smaller than or equal to 255.');
        }

        $this->container['country_name'] = $country_name;

        return $this;
    }

    /**
     * Gets ipfilter
     *
     * @return bool
     */
    public function getIpfilter()
    {
        return $this->container['ipfilter'];
    }

    /**
     * Sets ipfilter
     *
     * @param bool $ipfilter 
     *
     * @return $this
     */
    public function setIpfilter($ipfilter)
    {
        $this->container['ipfilter'] = $ipfilter;

        return $this;
    }

    /**
     * Gets on_demand_record
     *
     * @return int
     */
    public function getOnDemandRecord()
    {
        return $this->container['on_demand_record'];
    }

    /**
     * Sets on_demand_record
     *
     * @param int $on_demand_record 
     *
     * @return $this
     */
    public function setOnDemandRecord($on_demand_record)
    {
        $this->container['on_demand_record'] = $on_demand_record;

        return $this;
    }

    /**
     * Gets on_demand_record_code
     *
     * @return string
     */
    public function getOnDemandRecordCode()
    {
        return $this->container['on_demand_record_code'];
    }

    /**
     * Sets on_demand_record_code
     *
     * @param string $on_demand_record_code 
     *
     * @return $this
     */
    public function setOnDemandRecordCode($on_demand_record_code)
    {
        if (!is_null($on_demand_record_code) && (mb_strlen($on_demand_record_code) > 3)) {
            throw new \InvalidArgumentException('invalid length for $on_demand_record_code when calling Company., must be smaller than or equal to 3.');
        }

        $this->container['on_demand_record_code'] = $on_demand_record_code;

        return $this;
    }

    /**
     * Gets externallyextraopts
     *
     * @return string
     */
    public function getExternallyextraopts()
    {
        return $this->container['externallyextraopts'];
    }

    /**
     * Sets externallyextraopts
     *
     * @param string $externallyextraopts 
     *
     * @return $this
     */
    public function setExternallyextraopts($externallyextraopts)
    {
        if (!is_null($externallyextraopts) && (mb_strlen($externallyextraopts) > 65535)) {
            throw new \InvalidArgumentException('invalid length for $externallyextraopts when calling Company., must be smaller than or equal to 65535.');
        }

        $this->container['externallyextraopts'] = $externallyextraopts;

        return $this;
    }

    /**
     * Gets billing_method
     *
     * @return string
     */
    public function getBillingMethod()
    {
        return $this->container['billing_method'];
    }

    /**
     * Sets billing_method
     *
     * @param string $billing_method 
     *
     * @return $this
     */
    public function setBillingMethod($billing_method)
    {
        $allowedValues = $this->getBillingMethodAllowableValues();
        if (!in_array($billing_method, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'billing_method', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        if ((mb_strlen($billing_method) > 25)) {
            throw new \InvalidArgumentException('invalid length for $billing_method when calling Company., must be smaller than or equal to 25.');
        }

        $this->container['billing_method'] = $billing_method;

        return $this;
    }

    /**
     * Gets balance
     *
     * @return float
     */
    public function getBalance()
    {
        return $this->container['balance'];
    }

    /**
     * Sets balance
     *
     * @param float $balance 
     *
     * @return $this
     */
    public function setBalance($balance)
    {
        $this->container['balance'] = $balance;

        return $this;
    }

    /**
     * Gets show_invoices
     *
     * @return bool
     */
    public function getShowInvoices()
    {
        return $this->container['show_invoices'];
    }

    /**
     * Sets show_invoices
     *
     * @param bool $show_invoices 
     *
     * @return $this
     */
    public function setShowInvoices($show_invoices)
    {
        $this->container['show_invoices'] = $show_invoices;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id 
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets language
     *
     * @return int
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param int $language 
     *
     * @return $this
     */
    public function setLanguage($language)
    {
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets default_timezone
     *
     * @return int
     */
    public function getDefaultTimezone()
    {
        return $this->container['default_timezone'];
    }

    /**
     * Sets default_timezone
     *
     * @param int $default_timezone 
     *
     * @return $this
     */
    public function setDefaultTimezone($default_timezone)
    {
        $this->container['default_timezone'] = $default_timezone;

        return $this;
    }

    /**
     * Gets country
     *
     * @return int
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param int $country 
     *
     * @return $this
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return int
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param int $currency 
     *
     * @return $this
     */
    public function setCurrency($currency)
    {
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets transformation_rule_set
     *
     * @return int
     */
    public function getTransformationRuleSet()
    {
        return $this->container['transformation_rule_set'];
    }

    /**
     * Sets transformation_rule_set
     *
     * @param int $transformation_rule_set 
     *
     * @return $this
     */
    public function setTransformationRuleSet($transformation_rule_set)
    {
        $this->container['transformation_rule_set'] = $transformation_rule_set;

        return $this;
    }

    /**
     * Gets outgoing_ddi
     *
     * @return int
     */
    public function getOutgoingDdi()
    {
        return $this->container['outgoing_ddi'];
    }

    /**
     * Sets outgoing_ddi
     *
     * @param int $outgoing_ddi 
     *
     * @return $this
     */
    public function setOutgoingDdi($outgoing_ddi)
    {
        $this->container['outgoing_ddi'] = $outgoing_ddi;

        return $this;
    }

    /**
     * Gets voicemail_notification_template
     *
     * @return int
     */
    public function getVoicemailNotificationTemplate()
    {
        return $this->container['voicemail_notification_template'];
    }

    /**
     * Sets voicemail_notification_template
     *
     * @param int $voicemail_notification_template 
     *
     * @return $this
     */
    public function setVoicemailNotificationTemplate($voicemail_notification_template)
    {
        $this->container['voicemail_notification_template'] = $voicemail_notification_template;

        return $this;
    }

    /**
     * Gets fax_notification_template
     *
     * @return int
     */
    public function getFaxNotificationTemplate()
    {
        return $this->container['fax_notification_template'];
    }

    /**
     * Sets fax_notification_template
     *
     * @param int $fax_notification_template 
     *
     * @return $this
     */
    public function setFaxNotificationTemplate($fax_notification_template)
    {
        $this->container['fax_notification_template'] = $fax_notification_template;

        return $this;
    }

    /**
     * Gets invoice_notification_template
     *
     * @return int
     */
    public function getInvoiceNotificationTemplate()
    {
        return $this->container['invoice_notification_template'];
    }

    /**
     * Sets invoice_notification_template
     *
     * @param int $invoice_notification_template 
     *
     * @return $this
     */
    public function setInvoiceNotificationTemplate($invoice_notification_template)
    {
        $this->container['invoice_notification_template'] = $invoice_notification_template;

        return $this;
    }

    /**
     * Gets call_csv_notification_template
     *
     * @return int
     */
    public function getCallCsvNotificationTemplate()
    {
        return $this->container['call_csv_notification_template'];
    }

    /**
     * Sets call_csv_notification_template
     *
     * @param int $call_csv_notification_template 
     *
     * @return $this
     */
    public function setCallCsvNotificationTemplate($call_csv_notification_template)
    {
        $this->container['call_csv_notification_template'] = $call_csv_notification_template;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


