<?php
/**
 * OutgoingRoutingDetailed
 *
 * PHP version 5
 *
 * @category Class
 * @package  Delta\Voip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Brand REST API
 *
 * OpenAPI spec version: 2.17.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Delta\Voip\Model;

use \ArrayAccess;
use \Delta\Voip\ObjectSerializer;

/**
 * OutgoingRoutingDetailed Class Doc Comment
 *
 * @category Class
 * @package  Delta\Voip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OutgoingRoutingDetailed implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'OutgoingRouting-detailed';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'type' => 'string',
        'priority' => 'int',
        'weight' => 'int',
        'routing_mode' => 'string',
        'prefix' => 'string',
        'stopper' => 'bool',
        'force_clid' => 'bool',
        'clid' => 'string',
        'id' => 'int',
        'company' => '\Delta\Voip\Model\Company',
        'carrier' => '\Delta\Voip\Model\Carrier',
        'routing_pattern' => '\Delta\Voip\Model\RoutingPattern',
        'routing_pattern_group' => '\Delta\Voip\Model\RoutingPatternGroup',
        'routing_tag' => '\Delta\Voip\Model\RoutingTag',
        'clid_country' => '\Delta\Voip\Model\Country',
        'carrier_ids' => 'int[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'type' => null,
        'priority' => null,
        'weight' => null,
        'routing_mode' => null,
        'prefix' => null,
        'stopper' => null,
        'force_clid' => null,
        'clid' => null,
        'id' => null,
        'company' => null,
        'carrier' => null,
        'routing_pattern' => null,
        'routing_pattern_group' => null,
        'routing_tag' => null,
        'clid_country' => null,
        'carrier_ids' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'priority' => 'priority',
        'weight' => 'weight',
        'routing_mode' => 'routingMode',
        'prefix' => 'prefix',
        'stopper' => 'stopper',
        'force_clid' => 'forceClid',
        'clid' => 'clid',
        'id' => 'id',
        'company' => 'company',
        'carrier' => 'carrier',
        'routing_pattern' => 'routingPattern',
        'routing_pattern_group' => 'routingPatternGroup',
        'routing_tag' => 'routingTag',
        'clid_country' => 'clidCountry',
        'carrier_ids' => 'carrierIds'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'priority' => 'setPriority',
        'weight' => 'setWeight',
        'routing_mode' => 'setRoutingMode',
        'prefix' => 'setPrefix',
        'stopper' => 'setStopper',
        'force_clid' => 'setForceClid',
        'clid' => 'setClid',
        'id' => 'setId',
        'company' => 'setCompany',
        'carrier' => 'setCarrier',
        'routing_pattern' => 'setRoutingPattern',
        'routing_pattern_group' => 'setRoutingPatternGroup',
        'routing_tag' => 'setRoutingTag',
        'clid_country' => 'setClidCountry',
        'carrier_ids' => 'setCarrierIds'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'priority' => 'getPriority',
        'weight' => 'getWeight',
        'routing_mode' => 'getRoutingMode',
        'prefix' => 'getPrefix',
        'stopper' => 'getStopper',
        'force_clid' => 'getForceClid',
        'clid' => 'getClid',
        'id' => 'getId',
        'company' => 'getCompany',
        'carrier' => 'getCarrier',
        'routing_pattern' => 'getRoutingPattern',
        'routing_pattern_group' => 'getRoutingPatternGroup',
        'routing_tag' => 'getRoutingTag',
        'clid_country' => 'getClidCountry',
        'carrier_ids' => 'getCarrierIds'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const ROUTING_MODE__STATIC = 'static';
    const ROUTING_MODE_LCR = 'lcr';
    const ROUTING_MODE_BLOCK = 'block';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRoutingModeAllowableValues()
    {
        return [
            self::ROUTING_MODE__STATIC,
            self::ROUTING_MODE_LCR,
            self::ROUTING_MODE_BLOCK,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['type'] = isset($data['type']) ? $data['type'] : 'group';
        $this->container['priority'] = isset($data['priority']) ? $data['priority'] : null;
        $this->container['weight'] = isset($data['weight']) ? $data['weight'] : null;
        $this->container['routing_mode'] = isset($data['routing_mode']) ? $data['routing_mode'] : 'static';
        $this->container['prefix'] = isset($data['prefix']) ? $data['prefix'] : null;
        $this->container['stopper'] = isset($data['stopper']) ? $data['stopper'] : false;
        $this->container['force_clid'] = isset($data['force_clid']) ? $data['force_clid'] : false;
        $this->container['clid'] = isset($data['clid']) ? $data['clid'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['company'] = isset($data['company']) ? $data['company'] : null;
        $this->container['carrier'] = isset($data['carrier']) ? $data['carrier'] : null;
        $this->container['routing_pattern'] = isset($data['routing_pattern']) ? $data['routing_pattern'] : null;
        $this->container['routing_pattern_group'] = isset($data['routing_pattern_group']) ? $data['routing_pattern_group'] : null;
        $this->container['routing_tag'] = isset($data['routing_tag']) ? $data['routing_tag'] : null;
        $this->container['clid_country'] = isset($data['clid_country']) ? $data['clid_country'] : null;
        $this->container['carrier_ids'] = isset($data['carrier_ids']) ? $data['carrier_ids'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['priority'] === null) {
            $invalidProperties[] = "'priority' can't be null";
        }
        if (($this->container['priority'] < 0)) {
            $invalidProperties[] = "invalid value for 'priority', must be bigger than or equal to 0.";
        }

        if ($this->container['weight'] === null) {
            $invalidProperties[] = "'weight' can't be null";
        }
        if (($this->container['weight'] < 0)) {
            $invalidProperties[] = "invalid value for 'weight', must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getRoutingModeAllowableValues();
        if (!is_null($this->container['routing_mode']) && !in_array($this->container['routing_mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'routing_mode', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['routing_mode']) && (mb_strlen($this->container['routing_mode']) > 25)) {
            $invalidProperties[] = "invalid value for 'routing_mode', the character length must be smaller than or equal to 25.";
        }

        if (!is_null($this->container['prefix']) && (mb_strlen($this->container['prefix']) > 25)) {
            $invalidProperties[] = "invalid value for 'prefix', the character length must be smaller than or equal to 25.";
        }

        if ($this->container['stopper'] === null) {
            $invalidProperties[] = "'stopper' can't be null";
        }
        if (!is_null($this->container['clid']) && (mb_strlen($this->container['clid']) > 25)) {
            $invalidProperties[] = "invalid value for 'clid', the character length must be smaller than or equal to 25.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type 
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets priority
     *
     * @return int
     */
    public function getPriority()
    {
        return $this->container['priority'];
    }

    /**
     * Sets priority
     *
     * @param int $priority 
     *
     * @return $this
     */
    public function setPriority($priority)
    {

        if (($priority < 0)) {
            throw new \InvalidArgumentException('invalid value for $priority when calling OutgoingRoutingDetailed., must be bigger than or equal to 0.');
        }

        $this->container['priority'] = $priority;

        return $this;
    }

    /**
     * Gets weight
     *
     * @return int
     */
    public function getWeight()
    {
        return $this->container['weight'];
    }

    /**
     * Sets weight
     *
     * @param int $weight 
     *
     * @return $this
     */
    public function setWeight($weight)
    {

        if (($weight < 0)) {
            throw new \InvalidArgumentException('invalid value for $weight when calling OutgoingRoutingDetailed., must be bigger than or equal to 0.');
        }

        $this->container['weight'] = $weight;

        return $this;
    }

    /**
     * Gets routing_mode
     *
     * @return string
     */
    public function getRoutingMode()
    {
        return $this->container['routing_mode'];
    }

    /**
     * Sets routing_mode
     *
     * @param string $routing_mode 
     *
     * @return $this
     */
    public function setRoutingMode($routing_mode)
    {
        $allowedValues = $this->getRoutingModeAllowableValues();
        if (!is_null($routing_mode) && !in_array($routing_mode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'routing_mode', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        if (!is_null($routing_mode) && (mb_strlen($routing_mode) > 25)) {
            throw new \InvalidArgumentException('invalid length for $routing_mode when calling OutgoingRoutingDetailed., must be smaller than or equal to 25.');
        }

        $this->container['routing_mode'] = $routing_mode;

        return $this;
    }

    /**
     * Gets prefix
     *
     * @return string
     */
    public function getPrefix()
    {
        return $this->container['prefix'];
    }

    /**
     * Sets prefix
     *
     * @param string $prefix 
     *
     * @return $this
     */
    public function setPrefix($prefix)
    {
        if (!is_null($prefix) && (mb_strlen($prefix) > 25)) {
            throw new \InvalidArgumentException('invalid length for $prefix when calling OutgoingRoutingDetailed., must be smaller than or equal to 25.');
        }

        $this->container['prefix'] = $prefix;

        return $this;
    }

    /**
     * Gets stopper
     *
     * @return bool
     */
    public function getStopper()
    {
        return $this->container['stopper'];
    }

    /**
     * Sets stopper
     *
     * @param bool $stopper 
     *
     * @return $this
     */
    public function setStopper($stopper)
    {
        $this->container['stopper'] = $stopper;

        return $this;
    }

    /**
     * Gets force_clid
     *
     * @return bool
     */
    public function getForceClid()
    {
        return $this->container['force_clid'];
    }

    /**
     * Sets force_clid
     *
     * @param bool $force_clid 
     *
     * @return $this
     */
    public function setForceClid($force_clid)
    {
        $this->container['force_clid'] = $force_clid;

        return $this;
    }

    /**
     * Gets clid
     *
     * @return string
     */
    public function getClid()
    {
        return $this->container['clid'];
    }

    /**
     * Sets clid
     *
     * @param string $clid 
     *
     * @return $this
     */
    public function setClid($clid)
    {
        if (!is_null($clid) && (mb_strlen($clid) > 25)) {
            throw new \InvalidArgumentException('invalid length for $clid when calling OutgoingRoutingDetailed., must be smaller than or equal to 25.');
        }

        $this->container['clid'] = $clid;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id 
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets company
     *
     * @return \Delta\Voip\Model\Company
     */
    public function getCompany()
    {
        return $this->container['company'];
    }

    /**
     * Sets company
     *
     * @param \Delta\Voip\Model\Company $company company
     *
     * @return $this
     */
    public function setCompany($company)
    {
        $this->container['company'] = $company;

        return $this;
    }

    /**
     * Gets carrier
     *
     * @return \Delta\Voip\Model\Carrier
     */
    public function getCarrier()
    {
        return $this->container['carrier'];
    }

    /**
     * Sets carrier
     *
     * @param \Delta\Voip\Model\Carrier $carrier carrier
     *
     * @return $this
     */
    public function setCarrier($carrier)
    {
        $this->container['carrier'] = $carrier;

        return $this;
    }

    /**
     * Gets routing_pattern
     *
     * @return \Delta\Voip\Model\RoutingPattern
     */
    public function getRoutingPattern()
    {
        return $this->container['routing_pattern'];
    }

    /**
     * Sets routing_pattern
     *
     * @param \Delta\Voip\Model\RoutingPattern $routing_pattern routing_pattern
     *
     * @return $this
     */
    public function setRoutingPattern($routing_pattern)
    {
        $this->container['routing_pattern'] = $routing_pattern;

        return $this;
    }

    /**
     * Gets routing_pattern_group
     *
     * @return \Delta\Voip\Model\RoutingPatternGroup
     */
    public function getRoutingPatternGroup()
    {
        return $this->container['routing_pattern_group'];
    }

    /**
     * Sets routing_pattern_group
     *
     * @param \Delta\Voip\Model\RoutingPatternGroup $routing_pattern_group routing_pattern_group
     *
     * @return $this
     */
    public function setRoutingPatternGroup($routing_pattern_group)
    {
        $this->container['routing_pattern_group'] = $routing_pattern_group;

        return $this;
    }

    /**
     * Gets routing_tag
     *
     * @return \Delta\Voip\Model\RoutingTag
     */
    public function getRoutingTag()
    {
        return $this->container['routing_tag'];
    }

    /**
     * Sets routing_tag
     *
     * @param \Delta\Voip\Model\RoutingTag $routing_tag routing_tag
     *
     * @return $this
     */
    public function setRoutingTag($routing_tag)
    {
        $this->container['routing_tag'] = $routing_tag;

        return $this;
    }

    /**
     * Gets clid_country
     *
     * @return \Delta\Voip\Model\Country
     */
    public function getClidCountry()
    {
        return $this->container['clid_country'];
    }

    /**
     * Sets clid_country
     *
     * @param \Delta\Voip\Model\Country $clid_country clid_country
     *
     * @return $this
     */
    public function setClidCountry($clid_country)
    {
        $this->container['clid_country'] = $clid_country;

        return $this;
    }

    /**
     * Gets carrier_ids
     *
     * @return int[]
     */
    public function getCarrierIds()
    {
        return $this->container['carrier_ids'];
    }

    /**
     * Sets carrier_ids
     *
     * @param int[] $carrier_ids Carriers on LCR route type
     *
     * @return $this
     */
    public function setCarrierIds($carrier_ids)
    {
        $this->container['carrier_ids'] = $carrier_ids;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


