<?php
/**
 * AdministratorRelPublicEntityCollectionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Delta/Voip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Brand REST API
 *
 * OpenAPI spec version: 2.17.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Delta/Voip;

/**
 * AdministratorRelPublicEntityCollectionTest Class Doc Comment
 *
 * @category    Class
 * @description AdministratorRelPublicEntityCollection
 * @package     Delta/Voip
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdministratorRelPublicEntityCollectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AdministratorRelPublicEntityCollection"
     */
    public function testAdministratorRelPublicEntityCollection()
    {
    }

    /**
     * Test attribute "create"
     */
    public function testPropertyCreate()
    {
    }

    /**
     * Test attribute "read"
     */
    public function testPropertyRead()
    {
    }

    /**
     * Test attribute "update"
     */
    public function testPropertyUpdate()
    {
    }

    /**
     * Test attribute "delete"
     */
    public function testPropertyDelete()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "administrator"
     */
    public function testPropertyAdministrator()
    {
    }

    /**
     * Test attribute "public_entity"
     */
    public function testPropertyPublicEntity()
    {
    }
}
