<?php
/**
 * InvoiceNumberSequenceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Delta/Voip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Brand REST API
 *
 * OpenAPI spec version: 2.17.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Delta/Voip;

/**
 * InvoiceNumberSequenceTest Class Doc Comment
 *
 * @category    Class
 * @description InvoiceNumberSequence
 * @package     Delta/Voip
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceNumberSequenceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InvoiceNumberSequence"
     */
    public function testInvoiceNumberSequence()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "prefix"
     */
    public function testPropertyPrefix()
    {
    }

    /**
     * Test attribute "sequence_length"
     */
    public function testPropertySequenceLength()
    {
    }

    /**
     * Test attribute "increment"
     */
    public function testPropertyIncrement()
    {
    }

    /**
     * Test attribute "latest_value"
     */
    public function testPropertyLatestValue()
    {
    }

    /**
     * Test attribute "iteration"
     */
    public function testPropertyIteration()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }
}
