<?php
/**
 * BalanceNotificationDetailedTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Delta\Voip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Brand REST API
 *
 * OpenAPI spec version: 2.17.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Delta\Voip;

/**
 * BalanceNotificationDetailedTest Class Doc Comment
 *
 * @category    Class
 * @description BalanceNotificationDetailed
 * @package     Delta\Voip
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BalanceNotificationDetailedTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BalanceNotificationDetailed"
     */
    public function testBalanceNotificationDetailed()
    {
    }

    /**
     * Test attribute "to_address"
     */
    public function testPropertyToAddress()
    {
    }

    /**
     * Test attribute "threshold"
     */
    public function testPropertyThreshold()
    {
    }

    /**
     * Test attribute "last_sent"
     */
    public function testPropertyLastSent()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {
    }

    /**
     * Test attribute "notification_template"
     */
    public function testPropertyNotificationTemplate()
    {
    }
}
