<?php
/**
 * CarrierServerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Delta\Voip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Brand REST API
 *
 * OpenAPI spec version: 2.17.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Delta\Voip;

/**
 * CarrierServerTest Class Doc Comment
 *
 * @category    Class
 * @description CarrierServer
 * @package     Delta\Voip
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CarrierServerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CarrierServer"
     */
    public function testCarrierServer()
    {
    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {
    }

    /**
     * Test attribute "hostname"
     */
    public function testPropertyHostname()
    {
    }

    /**
     * Test attribute "port"
     */
    public function testPropertyPort()
    {
    }

    /**
     * Test attribute "uri_scheme"
     */
    public function testPropertyUriScheme()
    {
    }

    /**
     * Test attribute "transport"
     */
    public function testPropertyTransport()
    {
    }

    /**
     * Test attribute "send_pai"
     */
    public function testPropertySendPai()
    {
    }

    /**
     * Test attribute "send_rpid"
     */
    public function testPropertySendRpid()
    {
    }

    /**
     * Test attribute "auth_needed"
     */
    public function testPropertyAuthNeeded()
    {
    }

    /**
     * Test attribute "auth_user"
     */
    public function testPropertyAuthUser()
    {
    }

    /**
     * Test attribute "auth_password"
     */
    public function testPropertyAuthPassword()
    {
    }

    /**
     * Test attribute "sip_proxy"
     */
    public function testPropertySipProxy()
    {
    }

    /**
     * Test attribute "outbound_proxy"
     */
    public function testPropertyOutboundProxy()
    {
    }

    /**
     * Test attribute "from_user"
     */
    public function testPropertyFromUser()
    {
    }

    /**
     * Test attribute "from_domain"
     */
    public function testPropertyFromDomain()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "carrier"
     */
    public function testPropertyCarrier()
    {
    }
}
