<?php
/**
 * OutgoingRoutingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Delta\Voip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Brand REST API
 *
 * OpenAPI spec version: 2.17.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Delta\Voip;

/**
 * OutgoingRoutingTest Class Doc Comment
 *
 * @category    Class
 * @description OutgoingRouting
 * @package     Delta\Voip
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OutgoingRoutingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OutgoingRouting"
     */
    public function testOutgoingRouting()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "routing_mode"
     */
    public function testPropertyRoutingMode()
    {
    }

    /**
     * Test attribute "prefix"
     */
    public function testPropertyPrefix()
    {
    }

    /**
     * Test attribute "stopper"
     */
    public function testPropertyStopper()
    {
    }

    /**
     * Test attribute "force_clid"
     */
    public function testPropertyForceClid()
    {
    }

    /**
     * Test attribute "clid"
     */
    public function testPropertyClid()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {
    }

    /**
     * Test attribute "carrier"
     */
    public function testPropertyCarrier()
    {
    }

    /**
     * Test attribute "routing_pattern"
     */
    public function testPropertyRoutingPattern()
    {
    }

    /**
     * Test attribute "routing_pattern_group"
     */
    public function testPropertyRoutingPatternGroup()
    {
    }

    /**
     * Test attribute "routing_tag"
     */
    public function testPropertyRoutingTag()
    {
    }

    /**
     * Test attribute "clid_country"
     */
    public function testPropertyClidCountry()
    {
    }
}
