<?php
/**
 * TransformationRuleSetTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Delta\Voip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Brand REST API
 *
 * OpenAPI spec version: 2.17.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Delta\Voip;

/**
 * TransformationRuleSetTest Class Doc Comment
 *
 * @category    Class
 * @description TransformationRuleSet
 * @package     Delta\Voip
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransformationRuleSetTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TransformationRuleSet"
     */
    public function testTransformationRuleSet()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "international_code"
     */
    public function testPropertyInternationalCode()
    {
    }

    /**
     * Test attribute "trunk_prefix"
     */
    public function testPropertyTrunkPrefix()
    {
    }

    /**
     * Test attribute "area_code"
     */
    public function testPropertyAreaCode()
    {
    }

    /**
     * Test attribute "national_len"
     */
    public function testPropertyNationalLen()
    {
    }

    /**
     * Test attribute "generate_rules"
     */
    public function testPropertyGenerateRules()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }
}
