<?php
/**
 * MyApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Delta\Voip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Brand REST API
 *
 * OpenAPI spec version: 2.17.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Delta\Voip;

use \Delta\Voip\Configuration;
use \Delta\Voip\ApiException;
use \Delta\Voip\ObjectSerializer;

/**
 * MyApiTest Class Doc Comment
 *
 * @category Class
 * @package  Delta\Voip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MyApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getMyActiveCallsActiveCallsItem
     *
     * Retrieves a ActiveCalls resource..
     *
     */
    public function testGetMyActiveCallsActiveCallsItem()
    {
    }

    /**
     * Test case for getMyRegistrationSummaryRegistrationSummaryItem
     *
     * Retrieves a RegistrationSummary resource..
     *
     */
    public function testGetMyRegistrationSummaryRegistrationSummaryItem()
    {
    }
}
